dist: trusty
sudo: required
language:
- generic
cache:
- apt
env:
  global:
  - ROS_DISTRO=indigo
  - ROS_CI_DESKTOP="`lsb_release -cs`"
  - CI_SOURCE_PATH=$(pwd)
  - CATKIN_OPTIONS=$CI_SOURCE_PATH/catkin.options
  - ROS_PARALLEL_JOBS='-j8 -l6'
before_install:
- sudo sh -c "echo \"deb http://packages.ros.org/ros/ubuntu $ROS_CI_DESKTOP main\"
  > /etc/apt/sources.list.d/ros-latest.list"
- wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
- sudo apt-get update -qq
- sudo apt-get install -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-catkin
  ros-$ROS_DISTRO-object-recognition-core ros-$ROS_DISTRO-object-recognition-renderer
  ros-indigo-openni2-launch ros-indigo-urg-node ros-indigo-xsens-driver ros-indigo-joystick-drivers
  ros-indigo-navigation ros-indigo-pocketsphinx ros-indigo-rosserial ros-indigo-roboteq-diagnostics
  ros-indigo-roboteq-msgs ros-indigo-smach ros-indigo-rtabmap-ros ros-indigo-gazebo-ros
  ros-indigo-slam-gmapping ros-indigo-map-laser ros-indigo-moveit-full ros-indigo-geographic-info
  ros-indigo-zbar-ros ros-indigo-dynamixel-motor couchdb python-rosinstall libyaml-dev
  ros-indigo-soem espeak ros-indigo-object-recognition-core  ros-indigo-object-recognition-renderer
  ros-indigo-tf2-geometry-msgs
- source /opt/ros/$ROS_DISTRO/setup.bash
- sudo rosdep init
- rosdep update
install:
- mkdir -p ~/sara_ws/src
- cd ~/sara_ws/
- catkin_make
- source devel/setup.bash
- cd ~/sara_ws/src
- ln -s $CI_SOURCE_PATH
before_script:
- cd ~/sara_ws/src/sara_commun
- git submodule init
- git submodule update
- rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO
script:
- source /opt/ros/$ROS_DISTRO/setup.bash
- cd ~/sara_ws
- catkin_make
- source devel/setup.bash
- catkin_make run_tests && catkin_make test
notifications:
  slack:
    secure: n5sqHP5cNu5Won0NsPyloCZ9GZU7PH9x1NGUeUi0q2U64nNvSdXIsZVPWOklbVKHpfY72HmCofYQ/xZKkjyHLLLqY4YLHcuw+Q6m0aWeTc5JsEsMRgM2Mmauo4dxJfxvJyXdPQGqptOzfNZFjrULhJEn5881fCp6+p+zTW9fe63NWN9YgtKbVEGPyLdP326tYRB6dVewZEFqSQ/xWaP8pzIH3nZ9NpkyF/m1FlkuNBQm+NUTvcYBjleoc3HLxlQcBVQfFkcxSSzVG2FUO6t07HRiwDvmC1ZPmRRQ1jSdQUyngj1HebHKiS9YZ0yWX0uP4PwYryIe0KCp7WBmp1hDH/5BLNfrfcQspdDDZjn259E6BAu4Q0b87aFL/QUf0ysckc6PqSdkj5keKSj2loxYjqLOmCTfUwCrmdnwebFpBmSnj9GJliSRfMipE845ajioQmvuM3obmaTOZDJt/Wq1MQYMXRJe1gxZPjIwnR3SjtWqu+v6x+/ZHPz/vmcg2I8jHIfcczi2UTfZQv8QGZeWbnkKdTSl9bY+9OCNjbyBQrn3nqxVngtaT14lYsDb0EYUWCBcdiXRehROZR4GzaDP8JAu0HiZo5zUQBLpN/4sqZOP/1ygskppPoGvdH7rNSBFG3TMpGKzzE9Ge7cP3r5ns6czC5TxlVlhuyO17VV82kw=
