local_costmap:
  global_frame: /odom
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 8.0
  height: 8.0
  origin_x: 4.0
  origin_y: 4.0
  resolution: 0.05
  track_unknown_space: true
  cost_scaling_factor: 10.0 # default = 10.0
