DWAPlannerROS:

  #####################

  # The x acceleration limit of the robot in meters/sec^2
  # default: 2.5
  acc_lim_x: 10.0

  #The maximum x velocity for the robot in m/s.
  #default: 0.55s
  max_vel_x: 1.0

  #The minimum x velocity for the robot in m/s, negative for backwards motion.
  #default: 0.0
  min_vel_x: -0.1

  #####################

  # The y acceleration limit of the robot in meters/sec^2
  # default: 2.5
  acc_lim_y: 10.0

  # The maximum y velocity for the robot in m/s
  # default: 0.1
  max_vel_y: 0.2

  # The minimum y velocity for the robot in m/s
  # default: -0.1
  min_vel_y: 0.0

  #####################

  # The rotational acceleration limit of the robot in radians/sec^2
  # default: 3.2
  acc_lim_th: 10.0

  # The absolute value of the maximum rotational velocity for the robot in rad/s
  # default: 1.0
  max_rot_vel: 1aas.0

  # The absolute value of the minimum rotational velocity for the robot in rad/s
  # default: 0.4
  min_rot_vel: 0.4

  #####################

  # The absolute value of the maximum translational velocity for the robot in m/s
  # default: 0.55
  max_trans_vel: 1.2

  # The absolute value of the minimum translational velocity for the robot in m/s
  # default: 0.1
  min_trans_vel: 0.5

  #####################

  #The amount of time to forward-simulate trajectories in seconds
  sim_time: 1.6
  #The step size, in radians, to take between angular samples on a given trajectory
  angular_sim_granularity: 0.06
  sim_granularity: 0.05
  #The weighting for how much the controller should stay close to the path it was given. default 0.6
  pdist_scale: 0.25
  # The weighting for how much the controller should attempt to avoid obstacles. default 0.01
  occdist_scale: 0.3
  # The weighting for how much the controller should attempt to reach its local goal, also controls speed. default 0.8
  gdist_scale: 0.6

  # default: 0.2
  max_scaling_factor: 0.2

  # default 32.0
  path_distance_bias: 32.0

  # double, default: 24.0
  goal_distance_bias: 24.0

  # default true
  # Defines whether or not to eat up the plan as the robot moves along the path. If set to true, points will fall off
  #     the end of the plan once the robot moves 1 meter past them.
  prune_plan: true

  vx_samples: 8
  vtheta_samples: 12

  # default: 0.05
  yaw_goal_tolerance: 0.05

  # default: 0.10
  xy_goal_tolerance: 0.10
