#Set the tolerance we're willing to have for tf transforms
transform_tolerance: 0.3
planner_patience: 1.5
controller_patience: 1.5
recovery_behavior_enabled: true

track_unknown_space: false


obstacle_range: 4.0
raytrace_range: 5.0

# footprint: [[front left corner], [front right corner],
#             [rear right corner], [rear left corner]]
footprint: [[0.40, -0.33], [0.40, 0.33], [-0.40, 0.33], [-0.40, -0.33]]

inflation_radius: 0.10

observation_sources: laser_scan_sensor rgbd_camera_sensor

laser_scan_sensor: {sensor_frame: base_laser_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 32.0, inf_is_valid: false}

rgbd_camera_sensor: {sensor_frame: camera_link, data_type: PointCloud2, topic: /camera/depth_registered/points, marking: true, clearing: true, max_obstacle_height: 1.50, min_obstacle_height: 0.40}
